package:
  name: karpenter
  version: 1.0.5
  epoch: 0
  description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/karpenter-provider-aws
      tag: v${{package.version}}
      expected-commit: 652e6aaa53ad8c47c56eacaf85d7a0cae1459b6c

  - uses: go/build
    with:
      packages: ./cmd/controller
      output: controller
      ldflags: -X=sigs.k8s.io/karpenter/pkg/operator.Version=${{package.version}}

update:
  enabled: true
  github:
    identifier: aws/karpenter-provider-aws
    strip-prefix: v
