package:
  name: nri-kubernetes
  version: 3.29.5
  epoch: 0
  description: New Relic integration for Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-kubernetes
      tag: v${{package.version}}
      expected-commit: f14beedd78e02917aec960dd00b956941b59e74f

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS
      make compile
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bin/nri-kubernetes ${{targets.destdir}}/usr/bin/nri-kubernetes

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-kubernetes
    strip-prefix: v
    tag-filter: v
    use-tag: true
