package:
  name: py3-glpk
  version: 0.4.8
  epoch: 0
  description: PyGLPK, a Python module encapsulating GLPK.
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - gcc~13
      - glpk
      - openssf-compiler-options
      - py3-setuptools
      - py3-setuptools-scm
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: 419091b0dbbb061c83c64be2e038d1f29182b986627f8f8c4971601e17fbd013
      uri: https://files.pythonhosted.org/packages/source/g/glpk/glpk-${{package.version}}.tar.gz

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 37380
