package:
  name: py3-argcomplete
  version: 3.5.1
  epoch: 0
  description: Bash/zsh tab completion for argparse
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 252d5296f77457382e4370fc6252cf3abbcab201
      repository: https://github.com/kislyuk/argcomplete
      tag: v${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: kislyuk/argcomplete
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - uses: python/import
      with:
        import: argcomplete
      runs: |
        activate-global-python-argcomplete --help
        register-python-argcomplete version
    - runs: |
        register-python-argcomplete --help
