package:
  name: py3-termcolor
  version: 2.5.0
  epoch: 0
  description: ANSI color formatting for output in terminal
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-setuptools
      - python-3
      - wolfi-base
  environment:
    # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
    SOURCE_DATE_EPOCH: 315532800

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/termcolor/termcolor
      tag: ${{package.version}}
      expected-commit: 2654f7f2ae120aa2be69414d161867ec6ebf6f0a

  - runs: |
      python3 -m build
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl
      find ${{targets.destdir}} -name '*.pyc' -print -exec rm \{} \;

  - uses: strip

update:
  enabled: true
  github:
    identifier: termcolor/termcolor
    use-tag: true

test:
  environment:
    contents:
      packages:
        - python-3
  pipeline:
    - name: Verify installation
      runs: |
        python3 -c "import termcolor" || exit 1
    - name: Test colored output
      runs: |
        python3 -c 'from termcolor import colored; print(colored("Hello, World!", "red"))' | grep -q "Hello, World!" || exit 1
