package:
  name: py3-babel
  version: 2.16.0
  epoch: 0
  description: Python3 i18n tool
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/B/Babel/babel-${{package.version}}.tar.gz
      expected-sha256: d1f3554ca26605fe173f3de0c65f750f5a42f924499bf134de6423582298e316

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  shared: true
  release-monitor:
    identifier: 11984

test:
  pipeline:
    - runs: |
        LIBRARY="babel"
        IMPORT_STATEMENT="import babel"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
        pybabel --version
        pybabel --help
