package:
  name: py3-antlr4-python3-runtime
  version: 4.13.2
  epoch: 1
  description: ANTLR runtime for Python 3
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cc82115a4e7f53d71d9d905caa2c2dfa4da58899
      repository: https://github.com/antlr/antlr4
      tag: ${{package.version}}

  - uses: py/pip-build-install
    working-directory: runtime/Python3

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import antlr4
      runs: |
        pygrun --help
    - runs: pygrun --help

update:
  enabled: true
  github:
    identifier: antlr/antlr4
