package:
  name: py3-opt-einsum
  version: 3.4.0
  epoch: 0
  description: Optimizing numpys einsum function
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - numpy
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dgasmith/opt_einsum
      tag: v${{package.version}}
      expected-commit: c15aec2c7dbbcaf5b9790b980f699bf295baa7d9

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: dgasmith/opt_einsum
    strip-prefix: v

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import opt_einsum
